# Generated by Django 4.2.28 on 2026-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseenrollment",
            name="is_theory_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="theory_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
