# Generated by Django 4.2.28 on 2026-05-06 22:21

import courses.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_courseenrollment_progress_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=courses.models.course_media_upload_to),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "course_media",
                "ordering": ("-uploaded_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="coursemedia",
            constraint=models.UniqueConstraint(
                fields=("course", "slug"), name="unique_course_media_slug"
            ),
        ),
    ]
