# Generated by Django 4.2.28 on 2026-03-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0003_answeroption_created_at_answeroption_updated_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="useranswer",
            name="unique_question_per_attempt",
        ),
        migrations.AddField(
            model_name="testquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single_choice", "Single choice"),
                    ("multiple_choice", "Multiple choice"),
                ],
                default="single_choice",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="useranswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question", "selected_option"),
                name="unique_selected_option_per_question_attempt",
            ),
        ),
    ]
