# Generated by Django 4.2.28 on 2026-04-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0006_alter_answeroption_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="answeroption",
            constraint=models.UniqueConstraint(
                fields=("question", "order"), name="unique_option_order_per_question"
            ),
        ),
    ]
