# Generated by Django 4.2.28 on 2026-05-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_testattempt_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
