# Generated by Django 4.2.28 on 2026-03-22 00:00

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                default=5,
                validators=[MinValueValidator(1), MaxValueValidator(5)],
            ),
            preserve_default=False,
        ),
    ]
